# Generated by Django 5.2 on 2025-06-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('duracao', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Optativa',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField()),
                ('carga_horaria', models.PositiveSmallIntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaMatrizDisciplinasPreRequisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_disciplinamatriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_disciplinas', to='grafoNaHora.disciplinamatriz')),
                ('to_disciplinamatriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_disciplinas', to='grafoNaHora.disciplinamatriz')),
            ],
            options={
                'db_table': 'grafoNaHora_disciplinamatriz_disciplinas_prerequisitos',
                'unique_together': {('from_disciplinamatriz', 'to_disciplinamatriz')},
            },
        ),
        migrations.AddField(
            model_name='disciplinamatriz',
            name='disciplinas_prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_dependentes', through='grafoNaHora.DisciplinaMatrizDisciplinasPreRequisitos', to='grafoNaHora.disciplinamatriz'),
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('versao', models.PositiveSmallIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.curso')),
            ],
        ),
        migrations.AddField(
            model_name='disciplinamatriz',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.matriz'),
        ),
        migrations.AddField(
            model_name='disciplinamatriz',
            name='optativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.optativa'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('periodo', models.PositiveSmallIntegerField()),
                ('admin', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDisciplinasConcluidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.disciplinamatriz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.usuario')),
            ],
            options={
                'db_table': 'grafoNaHora_usuario_disciplinas_concluidas',
                'unique_together': {('usuario', 'disciplina')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='disciplinas_concluidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_concluintes', through='grafoNaHora.UsuarioDisciplinasConcluidas', to='grafoNaHora.disciplinamatriz'),
        ),
    ]
