# Generated by Django 5.2 on 2025-06-08 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafoNaHora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDisciplinasConcluidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.disciplinamatriz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.usuario')),
            ],
            options={
                'db_table': 'grafoNaHora_usuario_disciplinas_concluidas',
                'unique_together': {('usuario', 'disciplina')},
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='disciplinas_concluidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_concluintes', through='grafoNaHora.UsuarioDisciplinasConcluidas', to='grafoNaHora.disciplinamatriz'),
        ),
    ]
