# Generated by Django 5.2 on 2025-05-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafoNaHora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinamatriz',
            name='disciplinas_prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_que_dependem', to='grafoNaHora.disciplinamatriz'),
        ),
    ]
