# Generated by Django 5.2 on 2025-05-31 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafoNaHora', '0002_alter_disciplinamatriz_disciplinas_prerequisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinamatriz',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.disciplina'),
        ),
    ]
