# Generated by Django 5.2 on 2025-05-31 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafoNaHora', '0003_alter_disciplinamatriz_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinamatriz',
            name='disciplinas_prerequisitos',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplinas_que_dependem', to='grafoNaHora.disciplinamatriz'),
        ),
        migrations.AlterField(
            model_name='disciplinamatriz',
            name='optativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.optativa'),
        ),
    ]
