# Generated by Django 5.2 on 2025-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafoNaHora', '0004_alter_disciplinamatriz_disciplinas_prerequisitos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinamatriz',
            name='disciplinas_prerequisitos',
            field=models.ManyToManyField(null=True, related_name='disciplinas_que_dependem', to='grafoNaHora.disciplinamatriz'),
        ),
    ]
