# Generated by Django 5.2 on 2025-05-31 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafoNaHora', '0005_alter_disciplinamatriz_disciplinas_prerequisitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinamatriz',
            name='disciplinas_prerequisitos',
        ),
        migrations.AlterField(
            model_name='disciplinamatriz',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafoNaHora.disciplina'),
        ),
    ]
