# Generated by Django 5.2 on 2025-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafoNaHora', '0006_remove_disciplinamatriz_disciplinas_prerequisitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinamatriz',
            name='disciplinas_prerequisitos',
            field=models.ManyToManyField(blank=True, to='grafoNaHora.disciplinamatriz'),
        ),
    ]
